app:
  environment: prod

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DATABASE_POOL_SIZE}
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL}
        connection:
          provider_disables_autocommit: true
  security:
    token:
      secret: ${JWT_SECRET}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: ${CORS_ALLOWED_METHODS}
  allowed-headers: ${CORS_ALLOWED_HEADERS}
  exposed-headers: ${CORS_EXPOSED_HEADERS}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS}
  max-age: ${CORS_MAX_AGE}

rate-limit:
  requests: ${RATE_LIMIT_REQUESTS}
  duration: ${RATE_LIMIT_DURATION}

logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY}
    com.api.projects: ${LOG_LEVEL_APP}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL}
    org.hibernate.type: ${LOG_LEVEL_HIBERNATE_TYPE}
    org.springframework.web: ${LOG_LEVEL_WEB}
  file:
    name: ${LOG_FILE}
    max-size: 10MB
    max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized