spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  security:
    token:
      secret: secret-jwt-token-key-test