spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

cors:
  allowed-origins: http://localhost:5173
  allow-credentials: true

rate-limit:
  enabled: false