app:
  environment: dev

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/projects_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:create}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}
  security:
    token:
      secret: ${JWT_SECRET:secret-jwt-token-key-dev}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
  exposed-headers: ${CORS_EXPOSED_HEADERS:Authorization,Content-Type,X-Total-Count,X-Total-Pages}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
  max-age: ${CORS_MAX_AGE:3600}

rate-limit:
  requests: ${RATE_LIMIT_REQUESTS:10}
  duration: ${RATE_LIMIT_DURATION:60}

logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    com.api.projects: ${LOG_LEVEL_APP:DEBUG}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:false}
    org.hibernate.type: ${LOG_LEVEL_HIBERNATE_TYPE:false}
    org.springframework.web: ${LOG_LEVEL_WEB:DEBUG}