spring:
  application:
    name: projects
  datasource:
    url: jdbc:postgresql://localhost:5432/projects_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: false
  security:
    token:
      secret: secret-jwt-token-key

rate-limit:
  requests: 10
  duration: 60