spring:
  application:
    name: projects
  datasource:
    url: jdbc:postgresql://localhost:5432/projects_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: false
  security:
    token:
      secret: secret-jwt-token-key

cors:
  allowed-origins: "http://localhost:5173"
  allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
  allowed-headers: "Authorization,Content-Type"
  exposed-headers: Authorization,Content-Type,X-Total-Count,X-Total-Pages
  allow-credentials: true
  max-age: 3600

rate-limit:
  requests: 10
  duration: 60

logging:
  level:
    org.springframework.security: DEBUG
    com.api.projects: DEBUG